version: '3'

services: 
    db:
        container_name: postgres
        image: postgres:latest
        ports:
            - ${DATABASE_PORT}:5432
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_DB}
        volumes:
            - ./pgdata:/var/lib/postgresql/data

volumes:
    pgdata: