#!/bin/sh
FILE="$(dirname "$0")/_/husky.sh"
if [ ! -f "$FILE" ]; then
  cd server && npm install && npm run prepare && cd ../client && npm install && npm run prepare && cd ..
fi

. "$FILE"
cd server && npm install && cd ../client && npm install && cd ..
