#!/bin/sh
FILE="$(dirname "$0")/_/husky.sh"
if [ ! -f "$FILE" ]; then
  cd server && npm ci --legacy-peer-deps && npm run prepare && cd ../client && npm ci --legacy-peer-deps && npm run prepare && cd ..
fi

. "$FILE"
cd server && npm ci --legacy-peer-deps && cd ../client && npm ci --legacy-peer-deps && cd ..
