#!/bin/sh
FILE="$(dirname "$0")/_/husky.sh"
if [ ! -f "$FILE" ]; then
  cd server && npm ci && npm run prepare && cd ../client && npm ci && npm run prepare && cd ..
fi

. "$FILE"
cd server && npm ci && cd ../client && npm ci && cd ..
