#!/bin/sh
FILE="$(dirname "$0")/_/husky.sh"

DIFF=$(git diff --numstat $1 -- server/package.json)
DIFF2=$(git diff --numstat $1 -- client/package.json)

# Check if the variable gis empty
if [ -z "$DIFF" ]; then
  echo 'Server Package.json unchanged'
else
  if [ ! -f "$FILE" ]; then
    cd server && npm ci --legacy-peer-deps && npm run prepare && cd ..
  else
      . "$FILE"
      cd server && npm ci --legacy-peer-deps && cd ..
  fi

fi

if [ -z "$DIFF2" ]; then
  echo ' Client Package.json unchanged'
else
  if [ ! -f "$FILE" ]; then
    cd client && npm ci --legacy-peer-deps && npm run prepare && cd ..
  else
      . "$FILE"
      cd client && npm ci --legacy-peer-deps && cd ..
  fi

fi